// src/utils/permisosPorRol.js
const permisosPorRol = {
  admin: [
    "/",
    "/historial",
    "/admin",
    "/crear",
    "/cotizaciones",
    "/proveedores",
    "/editar",
    "/dashboard",
    "/logs",
    "/cargar-maestros",
    "/requerimientos",
    "/caja",
    "/resumen",
    "/indicadores",
    "/ver",
  ],
  comprador: [
    "/",
    "/historial",
    "/crear",
    "/firmar",
    "/cotizaciones",
    "/proveedores",
    "/editar",
    "/requerimientos",
    "/ver",
  ],
  operaciones: [
    "/",
    "/historial",
    "/firmar",
    "/dashboard",
    "/caja",
    "/ver",
  ],
  gerencia: [
    "/",
    "/historial",
    "/firmar",
    "/dashboard",
    "/ver",
  ],
  finanzas: [
    "/pago",
    "/pagos",
  ],
};
export default permisosPorRol;
